# Distributed revision control system
brew "git"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Tool for managing OCI containers and pods
brew "podman"
# Static type checker for Python
brew "pyright"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Terminal multiplexer
brew "tmux"
cask "font-jetbrains-mono-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Chromium-based web browser
cask "helium-browser"
# Software for Logitech devices
cask "logi-options+"
# Open-source code editor
cask "visual-studio-code"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "ms-vscode-remote.remote-containers"
